name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.1'
    - name: flutter doctor
      run: |
        flutter doctor -v
    - name: flutter package get
      run: |
        flutter pub get
    - name: Fill keystore key
      run: |
        CURPWD=$(pwd)
        echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > keystore.jks
        echo "storeFile=${CURPWD}/keystore.jks" > android/key.properties
        echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.ALIAS }}" >> android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties  
    - name: Build apk package
      run: |
        flutter build apk --release
    - name: Test app on apptest.ai
      uses: forcemax/apptestai-test@v1
      with:
        access_key: ${{ secrets.APPTEST_AI_ACCESS_KEY }}
        project_id: 1109 
        binary_path: build/app/outputs/apk/release/app-release.apk
